### ISSUE TITLE
Update tests of RT

### ISSUE THREAD

**Issue by JamesPino** [PNNL-CompBio/CONCERTO#12]
RT model has more gene ess. tests that I originally thought. They have Rb-TNrnaseq for various medias. Currently implemented M9 media but need generate for all.

The tests are not passing now due to naming. Currently the gene names in the model are "G_0001", but then parsed to "0001" (a string). When generating the gene list, it expects it to be the "0001" (a string). The way memote reads the file now ( and no way to control) is to infer type, thus resulting in 1 (int). So there is an not-so-useful error ```(KeyError: 'header')``` that pops up. A solution would be to rename the genes to 'RT_0001'. It seems like "G" is default when no prefix is given to there isn't an error like this one in other software.

**Comment by JamesPino** [comment]
@mcnaughtonadm do you know if cobra model always stores genes as string types? I can't find anywhere where it wouldn't be the case. 

in memote\experimental\essentiality.py, line 64, there is a dtype_conversion that is passed when loading the tablular data with pandas. I got the tests to run with this switch
`
dtype_conversion = {"essential": str}
`
to
`
dtype_conversion = {"essential": str, "gene": str}
`
in read_tabular, it also throws the comment column to str, so memote requires a lot. 

My question, if i do a PR with memote to add gene column conversion, would it be valid assumption that cobra store genes as str?

**Comment by JamesPino** [comment]
Solution: append RT to names of genes and biolog files

**Comment by djinnome** [comment]
evidence: In the file: https://github.com/PNNL-CompBio/CONCERTO/blob/update_rt_model/models/rhodosporidium_toruloides_ifo_08804/data/essentiality/ge_m9_glucose.csv

we observe protein ID:  10264 (Hexokinase) is essential in the RB-TnSeq data
We observe protein ID: 10264 (Hexokinase) is essential according to : https://fungalfit.genomics.lbl.gov/cgi-bin/exp.cgi?orgId=Rtoru&expName=setAAux_YNB_Gluc&show=important

Furthermore gene ID: 10264 (KOG0693Myo-inositol-1-phosphate synthase) with protein id [10136](https://mycocosm.jgi.doe.gov/cgi-bin/dispGeneModel?db=Rhoto_IFO0880_4&id=10136) 
is not essential either in the RB-TnSeq data, or in the [fungalfit data](https://fungalfit.genomics.lbl.gov/cgi-bin/exp.cgi?orgId=Rtoru&expName=setAAux_YNB_Gluc&show=important).

**Comment by djinnome** [comment]
Have these tests been updated with the correct protein IDs?

**Comment by JamesPino** [comment]
Yes, good to close!
