### ISSUE TITLE
Add invertase to Rhodo model

### ISSUE THREAD

**Issue by djinnome** [PNNL-CompBio/CONCERTO#17]
On the experimental side, we confirmed both from Pavlo and Biolog that Rhodo can grow on sucrose. On the computational side, we see that [RhodoCyc  has an invertase enzyme](https://cyc.pnnl.gov/NC12/NEW-IMAGE?type=REACTION&object=RXN-1461) and [computational studies identified SUC2](https://www.osti.gov/servlets/purl/1834456) which was confirmed by BLAST analysis to be 

```
>gnl|RHTO|G1DOZ-20580-MONOMER Beta-fructofuranosidase. (complement(join(835023..835852,835908..835965,836028..836146,836239..837165,837222..837288))) Rhodotorula toruloides scaffold_6
MVMNDVNGAF RAPNGTWHLY YQYNPTDVVA GNQHWGHATS DDMYHWVNQP IALFPPNSTA
AVFSGSAVTD PNNTSGFFPN NNASNPGVVA IYTLNTPEKQ TQEIAYSTDG GYSFTPYSGN
PVIDIGSNQF RDPKVIWYND RWVMTVAHAQ EMFIAIYTSQ NLKQWTEVSR FTRHGFTQLQ
YECPGLQRVP IRRRNATSSS GSSGSSGGSS NSSMSSSSSS APSSPVSTAS ASLARRQAST
LVSGASSLFS GASSVVRPSA SSAMSSGSRA SSTGSASSSS MISSGSSMAS ASSTASSAMP
SSTSTGGAAG GSSGGNSSSN SSSQDFAWVM WISINPGAPL GGSITQYFVG DFNGTHFTPF
DDSVKLADFG KDNYAGQFFY NTGDQAVSMA WASNWQYTDF VPTANELWRS ADSLPRNNYL
VEADRIGWVL ASEPYNISAV RNSSILPGGN ETTSLVNQTV SADFSNITSG AIYFSVNITL
PSNVTLGDYA SLNMTLTSAS SNENLTAGYF FGGPNSNSTW IDRSGTRGYT GNPFFTSQFS
QTAPTVAYNI EGVFDRSLFE LFIDEGTYAA TVDVYSQQPL TKIALATGDM PEGAQVQAAI
WGLSSVWTNS TSGGNSTSGG NSTNSAASSS MMSSTSSMMS SSSSMMSSMS STASAASTSA
SASTTA
```
 @JamesPino  if you submit a pull request with the changes, I will review it.

**Comment by djinnome** [comment]
Rhoto_IFO0880_4_14826

is the protein id in RhodoCyc

**Comment by JamesPino** [comment]
I believe this originated from an error in interpreting memote output.  The false negatives were 
```EX_succ_e,  EX_pro__L_e,  EX_for_e, EX_galur_e, EX_gly_e, EX_akg_e```

**Comment by djinnome** [comment]
I see. Since the rhodo model can grow on sucrose consistent with the Biolog observation, I think we can close this issue.
