### ISSUE TITLE
Ensure universal stoichiometric matrix can run in cobra

### ISSUE THREAD

**Issue by djinnome** [PNNL-CompBio/CONCERTO#22]

**Comment by mcnaughtonadm** [comment]
Found CobraPy compliant Universal BIGG Model [here](https://github.com/opencobra/cobrapy/wiki/BIGG-Universal-Model). This provides access to full Universal model with 15638 Reactions and 28301 metabolites. Able to generate necessary stoichiometric matrix and optimization through CobraPy.

**Comment by mcnaughtonadm** [comment]
Small Update: To use Gurobi with this universal model, you must first rename or remove the "St" bigg reaction. This just so happens to be a keyword in the LP files that gurobi constructs from the model and it will not process the file. This problem isn't present when using other solvers (it may happen using CPLEX), so just be aware.
