### ISSUE TITLE
2. Generate list of metabolites consumed and produced for each organism

### ISSUE THREAD

**Issue by djinnome** [PNNL-CompBio/CONCERTO#25]
If we write the code to do this now for each organism across all biolog conditions, then we can continuously update these lists as we iteratively improve the models.

**Comment by djinnome** [comment]
@JamesPino for those secreted metabolites for which we have experimental evidence (thanks to #26), should we create memote tests?

**Comment by vladpetyuk** [comment]
replaced by number of other more specific tasks
