### ISSUE TITLE
Create cyano/azo binary coculture

### ISSUE THREAD

**Issue by djinnome** [PNNL-CompBio/CONCERTO#34]

**Comment by mcnaughtonadm** [comment]
https://github.com/PNNL-CompBio/ConsortiumModels/commit/86d40acb2aa2ca171837cb310380885c3da4a217

Commit adding Binary SBML files

**Comment by mcnaughtonadm** [comment]
https://github.com/PNNL-CompBio/ConsortiumModels/blob/main/Notebooks/Binary_Consortium_AV_SE.ipynb

Notebook detailing integrating the binary model in MICOM
