### ISSUE TITLE
Create azo/rhodo binary coculture

### ISSUE THREAD

**Issue by djinnome** [PNNL-CompBio/CONCERTO#36]

**Comment by mcnaughtonadm** [comment]
https://github.com/PNNL-CompBio/ConsortiumModels/commit/86d40acb2aa2ca171837cb310380885c3da4a217

**Comment by mcnaughtonadm** [comment]
https://github.com/PNNL-CompBio/ConsortiumModels/blob/main/Notebooks/Binary_Consortium_AV_RT.ipynb
