### ISSUE TITLE
create team named CONCERTO under PNNL CompBio 

### ISSUE THREAD

**Issue by vladpetyuk** [PNNL-CompBio/CONCERTO#37]
Create an umbrella team for all the repositories that will be developed while working on the AIM1.
The repos will include:
* CONCERTO (Memote tests)
* rhodo model
* synecoccocus model
* azotobacter model

**Comment by djinnome** [comment]
We are already all members of the PPI team.  I can create a subteam, or just rename PPI to concerto

**Comment by djinnome** [comment]
Done
