### ISSUE TITLE
find biolog data for synecoccocus

### ISSUE THREAD

**Issue by vladpetyuk** [PNNL-CompBio/CONCERTO#48]

**Comment by djinnome** [comment]
Cristal Zuñiga, Tingting Li, Michael T Guarnieri, Jackson P Jenkins, Chien-Ting Li, Kerem Bingol, Young-Mo Kim, Michael J Betenbaugh, and Karsten Zengler. 2020. [Synthetic microbial communities of heterotrophs and phototrophs facilitate sustainable growth](https://doi.org/10.1038/s41467-020-17612-8). Nat. Commun. 11, 1 (July 2020), 3803. DOI:https://doi.org/10.1038/s41467-020-17612-8

[supplemenatry table](https://github.com/cristalzucsd/SyntheticMicrobialCommunities/blob/master/Tables%20Cyano_all.xlsx)

**Comment by vladpetyuk** [comment]
This biolog-derived data doesn't fit the purpose of growth test within MEMOTE.
