### ISSUE TITLE
Try loading cyano, rhodo, and azoto in Kbase prior to Monday meeting with Chris Henry

### ISSUE THREAD

**Issue by djinnome** [PNNL-CompBio/CONCERTO#86]
Prior to our meeting, let's create a few narratives in Kbase where we attempt to load each organism into KBase, and successfully produce nonzero growth.  If we can't that is ok, but at least attempt to do so.

Here is the attempt for Rhodo:
https://narrative.kbase.us/narrative/125544

**Comment by djinnome** [comment]
Here is how to merge metabolic models into a community:
https://narrative.kbase.us/#appcatalog/app/fba_tools/merge_metabolic_models_into_community_model/release

**Comment by mcnaughtonadm** [comment]
https://narrative.kbase.us/narrative/139180 - A narrative loading in each of the Genomes, still could not load in the correct Rhodosporidium model, seems like the integration with MycoCosm is not up to date? Can't pull the genome that way. Using a placeholder Rhodo model from NCBI we can load in each model and create community FBA models that way.

**Comment by mcnaughtonadm** [comment]
Process is as follows:

1. Load in Genome Object 
2. Build Metabolic Models (App) to create KBase FBAModels 
3. Merge FBAModels into Community FBAModel
4. Run FBA on that Community FBAModel
5. (Optional) Using SMETANA Beta app, calculate Metabolic Interaction Scores from FBAModels
