### ISSUE TITLE
ternary consortium does not have a dinitrogen flux

### ISSUE THREAD

**Issue by djinnome** [PNNL-CompBio/CONCERTO#87]
Hi @mcnaughtonadm 

The flux for `EX_n2_e` is zero in azotobacter for the [ternary consortia](https://github.com/PNNL-CompBio/CONCERTO/blob/flux_viz/ternary_consortium_fluxes_w_glc_and_sucr.csv).

Instead, it appears to be using $NO_3$ as the nitrogen source
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/144210/235322980-6d1077ab-14cf-45c6-b9e5-45a50af44db0.png)

Image thanks to @ShantMahserejian

**Comment by mcnaughtonadm** [comment]
Okay, looks like n2 isn't in the medium. Will rerun with it included.

**Comment by djinnome** [comment]
N2 is expensive to consume.  Might want to consider removing n03 from the media, too.

**Comment by djinnome** [comment]
Also just noticed that the medium appears to contain `glc__D` and `leu__L`  and does not appear to need `sucr__D`  
What changes to the consortia are needed to get it to grow using `co2` and `n2` as the only carbon and nitrogen sources?

**Comment by djinnome** [comment]
Hey @mcnaughtonadm thanks for pushing this task through to completion.  When @ShantMahserejian  has generated the new ternary alluvial diagram, we can close this issue

**Comment by mcnaughtonadm** [comment]
I ran the ternary under 2 new conditions:

1. With CO2 and N2 as the sole carbon and nitrogen sources provided in the combined media.
2. Same as 1. but with the photons reduced to only the 530 and 690 wavelengths. These are the only ""metabolites"" being used in FBA so this should clear some visual clutter of the alluvial.

[ternary_model_co2_n2_growth_reduced_photons.csv](https://github.com/PNNL-CompBio/CONCERTO/files/11537985/ternary_model_co2_n2_growth_reduced_photons.csv)
[ternary_model_co2_n2_growth.csv](https://github.com/PNNL-CompBio/CONCERTO/files/11537987/ternary_model_co2_n2_growth.csv)

**Comment by mcnaughtonadm** [comment]
This growth condition can help center some of the model curation that needs to be done as this provides incomplete community growth as is.

**Comment by ShantMahserejian** [comment]
![Alluvial_Diagram_Ternary_CO2_N2_Growth_ReducedPhotons](https://github.com/PNNL-CompBio/CONCERTO/assets/66797327/6091ea00-d428-4503-a9b7-e1691510315e)

Here's the alluvial diagram for the updated model and fluxes. 

- Note 1: The flux values have been log-log transformed to aid visualization
- Note 2: that Andrew passed me two flux files, one with reduced photon fluxes, though both produced the same diagram results

**Comment by djinnome** [comment]
This is fabulous! 
At first I was a bit surprised, because it appeared as if Rhodo was fixing CO2 (which would be bad), but then I saw that what it actually appears to be doing is converting CO2 to HCO3 (which isn't perfect, but is not nearly as bad).  Furthermore, it is clear that more CO2 is being consumed by Syn than is produced by Azo (which is good).   Ideally, we would separate out CO2 so that there is the flux of CO2 that is coming from the media, and then there is the CO2 that is exchanged, but if you don't have time for that, I can always explain why what appears counterintuitive still makes sense during the poster session if there is time.

**Comment by djinnome** [comment]
- [ ] For @mcnaughtonadm  create a source metabolite for co2 and h2o and o2
- [ ] For @ShantMahserejian create new source metabolites on the left-hand side of the alluvial diagram
- [ ] For @mcnaughtonadm remove the reaction that converts co2 to hco3 in rhodo and see if we can remove a confusing flux
- [ ] What happened to the excreted metabolites?  Is this because there is no-growth?
- [ ] Should we have a flux for biomass (even though it isn't technically an exchange metabolite. It seems to be a good sink metabolite
