### ISSUE TITLE
Updating the Cyano confusion matrix with the new model

### ISSUE THREAD

**Issue by djinnome** [PNNL-CompBio/CONCERTO#94]
Hi @JamesPino 

According to [Santos-Merino 2023](https://doi.org/10.3389/fmicb.2023.1126030), they reported the following confusion matrix:

![Screen Shot 2023-05-30 at 7 55 54 PM](https://github.com/PNNL-CompBio/CONCERTO/assets/144210/3c39ecab-f60e-4169-b04b-be501ecd5e3b)

Can we run [this updated cyano model](https://github.com/PNNL-CompBio/CONCERTO/files/11607223/Data_Sheet_3_Highlighting.the.potential.of.Synechococcus.elongatus.PCC.7942.as.platform.to.produce._-linolenic.acid.through.an.updated.genome-scale.me.ZIP) on the phenotype observations we have collected for Cyano to see if we get similar numbers?

[1] María Santos-Merino, Álvaro Gargantilla-Becerra, Fernando de la Cruz, and Juan Nogales. 2023. [Highlighting the potential of Synechococcus elongatus PCC 7942 as platform to produce α-linolenic acid through an updated genome-scale metabolic modeling](https://doi.org/10.3389/fmicb.2023.1126030). Front. Microbiol. 14, (March 2023), 1126030.

**Comment by djinnome** [comment]
Hey @JamesPino , were you able to get final numbers for the new cyano confusion matrix?

**Comment by JamesPino** [comment]
[328 142]
 [ 71 244]

**Comment by djinnome** [comment]
TP: 328
FN: 142
FP: 71
TN: 244

<table>
<tr><th>Cyano</th><th></th><th colspan=3> Predicted Growth</th><tr>
<tr><th rowspan=4>Actual Growth<th></th><th>+</th><th> -</th></tr>
<tr><th>+</th><td>244</td><td>142</td></tr>
<tr><th>-</th><td>71</td><td>328</td></tr>
</table>

**Comment by JamesPino** [comment]
![confusion_matrix](https://github.com/PNNL-CompBio/CONCERTO/assets/3987544/06b06013-6f43-4356-a6d9-ba1dfb652051)
